### ISSUE TITLE
What distributions should we use?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#11]
What distributions should we program?  The design doc says “skewed” and “symmetrical” but doesn’t mention gaussian or other distributions (as far as I can tell in a search).

**Comment by samreid** [comment]
At today's design meeting, @amanda-phet said she would give us a function or distribution.  

@kathy-phet said @amanda-phet could provide a table with probabilities per cell (normalized to 1).
@amanda-phet asks if all users will see the same distributions, or if it will be randomized from session to session.
@kathy-phet says they can ask with their consulting meeting today, when they discuss with the team.
@kathy-phet says we can use a seed to pick between a set of discrete pre-determined distributions.

@amanda-phet says the spread screen will have 3 or 4 distributions, associated with the T-shirt icons.

@samreid says that since the sim is discrete, a table will be fine.
@amanda-phet says reducing the range to be 1-10 instead of 1-16 may be OK.  But we have also discussed the need to have more than 10 balls.  It is difficult to see a distribution with only 10 balls spread across 16 slots.

**Comment by samreid** [comment]
Can you please provide tables in the form:

```
0, 2, 4, 7, 8, 9, 10, 6, 4, 4, 4, 2, 0, 0, 0, 0
```

We will assert that it has the right number of entries, and we will normalize it.  And my understanding is that we will use it as a probability distribution rather than exact ratios, is that correct?

**Comment by chrisklus** [comment]
From 2/25 design meeting:

@amanda-phet will get the latest values on March 1st, but provide sample data on the 28th in the above form.

**Comment by samreid** [comment]
I added a sampling algorithm that is ready to use data in the form described in https://github.com/phetsims/center-and-spread/issues/11#issuecomment-1050500778

**Comment by amanda-phet** [comment]
Please use these two distributions for both the Median and Mean & Median screens (randomly chosen when the sim/screen starts, and reset): 

skewed left: `[0.01832,0.07326,0.14653,0.19537,0.19537,0.15629,0.1042,0.05954,0.02977,0.01323,0.00529,0.00192,0.00064,0.0002,0.00007]` 

skewed right: `[0.00007,0.0002,0.00064,0.00192,0.00529,0.01323,0.02977,0.05954,0.1042,0.15629,0.19537,0.19537,0.14653,0.07326,0.01832]` 

These are the same values, just mirrored, so feel free to use one set and just "flip" it around if that works for you.

**Comment by samreid** [comment]
I added the prescribed distributions, flip it in the code, and choose randomly on startup and reset all (but not when the eraser is pressed).  Ready for review.

**Comment by amanda-phet** [comment]
I'm not getting the effect I would like to see with this distribution. Would you mind using this instead? (Otherwise happy with the behavior!) 

`[4, 8, 12, 16, 13, 11, 9, 7, 6, 5, 4, 3, 1, .5, .5]`

**Comment by samreid** [comment]
I updated the distribution, ready for testing.

**Comment by amanda-phet** [comment]
Final distribution for now, and you can close after implementing. Thank you!

[6, 9, 11, 14, 11, 8, 6, 5, 5, 5, 5, 5, 5, 5, 5]

**Comment by samreid** [comment]
I added the new distribution, closing.
