### ISSUE TITLE
Mockup screenshots have discrepancies

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#16]
During development, @chrisklus and I have seen many occurrences where different mockups show different patterns, and we cannot tell which is the more recent or desired one.  For instance, today we saw this mockup for screen 2:

![image](https://user-images.githubusercontent.com/679486/153241867-37a68b48-256d-4600-99e6-ce30fff7cb4e.png)

Then just below, this screenshot for screen 2:

![image](https://user-images.githubusercontent.com/679486/153241923-e22dee06-977c-4fad-ba58-a0f6a59f2f79.png)

It would be efficient for us to have a uniform and up-to-date set of mock-ups as we go through this initial phase.

Also, regarding timing:  These discrepancies are slowing us down a bit, but also if it would be tedious or take a long time to update all the screenshots, maybe we should use a different strategy.  We don't want @amanda-phet to take 10 hours updating mockups if it will only save us 2 hours, for example.

**Comment by amanda-phet** [comment]
This often happens with mockups when we change something in one place and forget to transfer it to other places. It would probably be most efficient to ask about a discrepancy in slack and I can confirm which drawing is correct. 

In the example above, we want the second screenshot that only has strings for "Mean" and "Median"  with an image next to it.

**Comment by samreid** [comment]
Sounds good, we will just ask when we are unclear.
