### ISSUE TITLE
How should we animate the number cards when sorting?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#17]
The two simple ways of sorting that @samreid and I tried out are:

1. Animate all cards to their destination spot at the same time, all at the same animation speed. This is a lot of moving parts at once, but you tend to be able to watch the last few go into place since cards that have farther to go take longer.

2. Animate all cards to their destination spot at the same time, all with the same duration of animation. This is also a lot of moving parts at once, but feels like a smooth overall transition because they all finish at the same time, though you don't necessarily watch any one card.

3. Sort the cards one at a time, so students can watch how sort is happening. The method we thought of for this would find the next lowest card that is out of place and move it to the correct spot. This would be a longer overall animation (maybe only 2-3 seconds), but would be very clear what is happening. @samreid and I spent some time starting this way, but it will take longer and we didn't think we should continue without knowing if it was the desired design. We think this will be clearest and is worth more investigation, and estimate probably a little more than an hour to finish the implementation we started.

4. Another option that is like 3 is a version that sends all cards with same value at the same time. So it still sends in order from smallest to largest, but instead of one card at a time, it's one value group at a time. We think this would be more like 30 minutes to implement. @samreid is thinking of this a worse version of 3.

@chrisklus prefers 2 to 1 if we don't do 3 or 4.

patch for options 3 in progress:
<details/>

```diff
Index: js/common/view/NumberCardContainer.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/NumberCardContainer.ts b/js/common/view/NumberCardContainer.ts
--- a/js/common/view/NumberCardContainer.ts	(revision 3cbc6f43b9a79b4bfe3c4f499b58395cab00bf98)
+++ b/js/common/view/NumberCardContainer.ts	(date 1644429697253)
@@ -179,27 +179,67 @@
       }
     } );
 
+    const isCardInWrongSpot = ( cardNodeToCheck ) => {
+      const visibleCardNodes = getVisibleNumberCardNodes();
+
+      const cardNodeToCheckValue = cardNodeToCheck.casObject.valueProperty.value;
+      const cardNodeToCheckPositionX = cardNodeToCheck.casObject.positionProperty.value.x;
+
+      for ( let j = 0; j < visibleCardNodes.length; j++ ) {
+        const cardNode = visibleCardNodes[ j ];
+        const cardValue = cardNode.casObject.valueProperty.value!;
+        const cardPositionX = cardNode.casObject.positionProperty.value.x;
+
+        if ( cardValue > cardNodeToCheckValue && cardPositionX < cardNodeToCheckPositionX ) {
+          return false;
+        }
+      }
+    };
+
+    const sendToFront = () => {
+      const visibleCardNodes = getVisibleNumberCardNodes();
+
+      let minimumValue = 100;
+      let cardToMove = null;
+
+      for ( let i = 1; i <= 16; i++ ) {
+        const cardsWithValue = visibleCardNodes.filter( cardNode => cardNode.casObject.valueProperty.value === i );
+
+        for ( let j = 0; cardsWithValue.length; j++ ) {
+          const cardNode = visibleCardNodes[ j ];
+          if ( isCardInWrongSpot( cardNode ) ) {
+
+          }
+        }
+      }
+
+      // If the card is visible, the value property should be non-null
+      const sorted = _.sortBy( visibleCardNodes, cardNode => cardNode.casObject.valueProperty.value );
+
+    };
+
     model.isSortingDataProperty.link( isSortingData => {
-      if ( isSortingData ) {
-        const visibleCardNodes = getVisibleNumberCardNodes();
+        if ( isSortingData ) {
+          const visibleCardNodes = getVisibleNumberCardNodes();
 
-        // If the card is visible, the value property should be non-null
-        const sorted = _.sortBy( visibleCardNodes, cardNode => cardNode.casObject.valueProperty.value );
+          // If the card is visible, the value property should be non-null
+          const sorted = _.sortBy( visibleCardNodes, cardNode => cardNode.casObject.valueProperty.value );
 
-        for ( let i = 0; i < sorted.length; i++ ) {
-          const cardNode = sorted[ i ];
+          for ( let i = 0; i < sorted.length; i++ ) {
+            const cardNode = sorted[ i ];
 
-          const destination = new Vector2( getCardPositionX( i ), 0 );
-          const distance = cardNode.positionProperty.value.distance( destination );
+            const destination = new Vector2( getCardPositionX( i ), 0 );
+            const distance = cardNode.positionProperty.value.distance( destination );
 
-          // TODO: Should we show a more natural sort, like sending the lowest number to the left first, etc.
-          // speed = distance/time
-          // time = distance/speed
-          const time = distance / 20 / 10;
-          cardNode.animateTo( destination, time );
+            // TODO: Should we show a more natural sort, like sending the lowest number to the left first, etc.
+            // speed = distance/time
+            // time = distance/speed
+            const time = distance / 20 / 10;
+            cardNode.animateTo( destination, time );
+          }
         }
       }
-    } );
+    );
   }
 }
 
```

**Comment by amanda-phet** [comment]
Discussed this with the pedagogy design team and we decided to go with option 3. I think most users will click "sort data" once, and likely leave it sorted, so it's ok that it will take a little longer to complete. 

We also thought it would be fun to have an easter egg in the sim if a user manually sorts the data and gets it correctly sorted from least to greatest, and would like to discuss this at design meeting.

**Comment by chrisklus** [comment]
From 2/25 design meeting:

We would like this by the 4th.

**Comment by chrisklus** [comment]
This is ready for an initial review by @amanda-phet.

We are currently animating each sort step for .5 seconds, and then pausing for .2 seconds between each sort. Without the pause, it felt difficult to see what was happening. Looking at it a bit more now, it seems like it might be nice to have the cards move at more of a consistent speed than a consistent time per step, as cards that go far distances are pretty hard to track.

**Comment by amanda-phet** [comment]
I would like to consider making this overall much faster.. so maybe the sort step is .3 seconds and the pause is .1 seconds. Should we look at this during Wednesday's meeting? 

>Looking at it a bit more now, it seems like it might be nice to have the cards move at more of a consistent speed than a consistent time per step, as cards that go far distances are pretty hard to track.

I didn't find it too hard to track, but I'm also good with trying this out. 

I also want to look at the sorting algorithm again... right now it seems to move left to right and put each card in order in that way. I would ideally prefer if the lowest value is sorted first, then the next lowest value, and so on. If it would help to discuss or put some specific examples here I can do that.

**Comment by chrisklus** [comment]
>I would like to consider making this overall much faster.. so maybe the sort step is .3 seconds and the pause is .1 seconds. Should we look at this during Wednesday's meeting?

I committed this change above, and it's visible in the following screen recording.

>I also want to look at the sorting algorithm again... right now it seems to move left to right and put each card in order in that way. I would ideally prefer if the lowest value is sorted first, then the next lowest value, and so on. If it would help to discuss or put some specific examples here I can do that.

Oops, yes we definitely were thinking that originally but accidentally implemented a different sort method.

One thing we discovered that we wanted to point out that might be an issue (for the existing sort and the sort that it should be) is in cases like this:

https://user-images.githubusercontent.com/5618316/156256329-2ae03709-5e88-4820-8382-66fe5138ad39.mp4

Noting the computer clock in the screen recording, that took about 5 seconds just to move the 15 to the end.

**Comment by samreid** [comment]
Let's discuss whether the desired behavior is acceptable before working more on the implementation.  We can always do the all the cards move at once" strategy we started with.

**Comment by amanda-phet** [comment]
Discussed 3/2/22 and decided it's probably not worth the time investment to continue refining a sort that is a more "pedagogical" approach. Instead we would like to revert back to the previous sort, which was quick and clear and looked nice.

**Comment by samreid** [comment]
I reverted the sort to all cards at once, @amanda-phet can you please review?  Please close if all is well.

**Comment by amanda-phet** [comment]
Looks good. Thanks!
