### ISSUE TITLE
How many data objects should be allowed on each screen?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#20]
See https://github.com/phetsims/center-and-spread/issues/11#issuecomment-1034135509

> @amanda-phet says reducing the range to be 1-10 instead of 1-16 may be OK. But we have also discussed the need to have more than 10 balls. It is difficult to see a distribution with only 10 balls spread across 16 slots.

**Comment by samreid** [comment]
@chrisklus is anything else necessary here for the classroom prototype?

**Comment by chrisklus** [comment]
@samreid and I reviewed together and we think this issue is complete for all 4 screens, closing.
