### ISSUE TITLE
Should the z-order of number cards be set intentionally?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#21]
@samreid and I noticed that sometimes the animating cards feel like the have an incorrect z-position when they are being sorted. We would like to try out showing cards with the longest distance to travel to be in front (but still behind any dragged cards) so that we don't see cards passing behind multiple stationary cards.

We had two more thoughts:

We might not need this at all if we implement option 3 from https://github.com/phetsims/center-and-spread/issues/17 because they would animate one at a time.

If we do want it, we might be able to get away with a simple rule like move a card to the front when it starts animating, then move any cards being dragged to the front, and move a card to the back when it stops animating. This should ensure that there are no traveling cards passing behind stationary cards, which feel more buggy than two cards in motion passing each other in opposite directions having a non-determined z-order.

**Comment by samreid** [comment]
Since we agreed on option 3 from #17, this issue is likely to be unnecessary.  We can reopen it or a new issue if other z-ordering questions arise.  Closing.
