### ISSUE TITLE
It seems odd that "kick 5" might not kick 5 balls

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#25]
Discovered in https://github.com/phetsims/center-and-spread/issues/23.

On January 5, 2022, we said:

> Discussed having the button always say kick 10, even if it’s “up to 10” 

Seeing the sim in context, it doesn't seem ideal that pressing "kick 5" might only kick, say, 3 balls.  There are some straightforward remedies:

* The "kick 5" button could be grayed out and the user could press "kick 1" three times.
* The "kick 5" button label could change to "kick 3"
* The "kick 5" button label could change to "kick all"
* The "kick 5" button label could change to "kick"

I also considered showing an icon instead of a number, thinking if the "kick 5" button had 5 ball icons, then it could show 4 icons instead if there were only 4 balls left (like it is the supply that is running out).  I quickly made a mock-up but have to admit it doesn't look as good as I thought it might.  But I'll share it here in case someone can improve on it, or in case it inspires better ideas:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/679486/153552596-bc79d40e-9540-46f9-a735-21bcacf1815f.png">

@amanda-phet what do you think?

**Comment by samreid** [comment]
One minor adjustment that partially stacks the ball icons instead of overlapping left to right. Again, thought this would look better than it did:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/679486/153553262-587f9cfc-fea4-4dc8-a570-6b2c068f27b3.png">

**Comment by amanda-phet** [comment]
I am OK with either of the following options: 
(1) Kick ≤5 depending on how many have been kicked in total, and keep the label as "Kick 5" (similar to Plinko) 
(2) Gray out the "Kick 5" button if <5 balls are remaining

**Comment by amanda-phet** [comment]
Assigning others to get input on which direction to go.

**Comment by samreid** [comment]
Since "Kick 5" kicking 2 balls feels buggy and may be perceived as buggy, I decided to implement the "(2) Gray out the "Kick 5" button if <5 balls are remaining" strategy so we could test it out.  It will be easy to revert if we decide against it.

**Comment by ariel-phet** [comment]
Just as a thought we could also go with something more ambiguous like "Kick Many" and have it kick 5 at a time, and then if less than 5 left it still kick the remaining ones. But graying out the button also seem reasonable if there are not 5 left to kick.

**Comment by samreid** [comment]
Here's a mock-up of Kick 1 vs Kick Many:

![image](https://user-images.githubusercontent.com/679486/154148982-6544b764-5c29-4844-bfb7-2b75e268a8ad.png)

**Comment by amanda-phet** [comment]
Discussed 2/16/22. @kathy-phet and I like the options I presented in https://github.com/phetsims/center-and-spread/issues/25#issuecomment-1039483200 but @samreid and @chrisklus want to try this option: 
>The "kick 5" button label could change to "kick 3"

**Comment by samreid** [comment]
@chrisklus and I added prototype code for the "Kick N" button so the team can see how it behaves.  If we agree it's for the best, we would probably improve some of this code and add i18n.

We also felt it odd to see 2 grayed out "Kick 1" buttons when all balls are depleted, so we tried making the buttons invisible instead of disabled and it seemed like an improvement.  So that's also in this version.  But we aren't sure whether a11y or the pdom would prefer disabled buttons to invisible buttons.

During today's meeting we discussed that it would be odd to see two "Kick 1" buttons next to each other.  In our experience with this feature, we considered that:
* It would be rare to get in that state.  The user would have to kick exactly 14 balls and then stop kicking.
* It would be a rare transient state.  We have see that users often keep kicking until all 15 balls have been kicked.

So we thought that the two "kick 1" buttons probably shouldn't rule out this strategy.

@amanda-phet @kathy-phet @ariel-phet what do you think?
https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.6/phet/center-and-spread_en_phet.html

**Comment by ariel-phet** [comment]
The current solution seems to work well to me. Seeing Kick 1 and Kick 1 together is not confusing if you have seen the "multiple kicks button" count down, and as you pointed out will be fairly rare.

**Comment by samreid** [comment]
Nobody mentioned a problem with this during the last design meeting.  Perhaps it is OK?  If not, please reopen.

**Comment by amanda-phet** [comment]
I should have replied here that it's fine with me if others are happy with it.
