### ISSUE TITLE
Holding "kick 1" should fire multiple times

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#34]

**Comment by samreid** [comment]
I added this support, but could use help because in some runs, holding down the Kick 5 button doesn't deplete all the kickers.

**Comment by chrisklus** [comment]
@samreid and I decided that we would try turning off fire-on-hold for "Kick 5", as enabling it felt like nested multi-kicking, which seems weird.

@amanda-phet this is ready for review, and please note the related question over in https://github.com/phetsims/center-and-spread/issues/53.

**Comment by amanda-phet** [comment]
This is working for me. 

I think once we implement the new artwork and address #53 we might want to implement the same solution for artwork for kick 5 as we do for holding kick 1.
