### ISSUE TITLE
Consistent use of colors, like 'white' vs Color.WHITE

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#37]
The sim currently has inconsistent use, with `'white'` and `Color.WHITE` appearing even in the same file.  It doesn't seem like there is a convention for this across the project--more like developer preference.  But the sim should be internally consistent. 

We also talked about ColorDef may one day want to support a string literal union of supported string types.  That may encourage us to go the string route more often.

**Comment by samreid** [comment]
I saw that we require hex strings, hence it seems acceptable to go all in on strings.  @chrisklus can you please review?  Close if all is well.

**Comment by chrisklus** [comment]
Looks good, thanks! Closing.
