### ISSUE TITLE
Sim name and third screen are named "Center and Spread"

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#4]
@samreid and I noticed that the sim name and the third screen and both named "Center and Spread" while we were starting to setup the repo structure. I find this odd, and @samreid pointed out that when the sim is loaded with `screens=3`, the nav bar title will read "Center and Spread - Center & Spread".

Assigning to @amanda-phet for next steps if anything should be changed here.

**Comment by amanda-phet** [comment]
Let's just change screen 3 to "Spread."

**Comment by samreid** [comment]
I'll do this momentarily.

**Comment by samreid** [comment]
OK it was renamed.  @chrisklus would you like to review?

**Comment by chrisklus** [comment]
Changes look great, thanks! I really like this name change, especially from a code perspective. Closing.
