### ISSUE TITLE
Add query parameter/preferences option for "line plot"

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#40]
We need a query parameter and preferences dialog option for line plot. This must do two things: 
1. Change all filled circles in the dot plot to be x's 
2. Change the title of the accordion box to be Line Plot

![image](https://user-images.githubusercontent.com/7852916/155399453-94b44732-d75e-4a1b-a0cb-c79a33b8d4c1.png)

I'm not sure what the query parameter should be- boolean? `linePlot=true`? I'm not good at determining this kind of thing. 

For the preferences dialog, should it be a checkbox option? A toggle switch? (Dot Plot <-> Line Plot).

**Comment by kathy-phet** [comment]
Maybe it should be an enum in PhET-iO? Some thoughts
query: 
plotType="dotPlot" plotType="linePlot"

enum: 
plotType="LINEPLOT" "DOTPLOT"

**Comment by samreid** [comment]
How about `?plotType=line` with the default being `dot`.  Then we will match the PhET-iO interface accordingly.

**Comment by kathy-phet** [comment]
I think we need to say "linePlot" in the choice. Because just "line" is too confusing all by itself. 

We could say ?plotMarker=dot or ?plotMarker=cross, but its more aligned with the math resources/pedagogy to use linePlot and dotPlot.

**Comment by chrisklus** [comment]
This is needed for March 4th - at the least, dots should be rendered as X's instead of dots.

**Comment by samreid** [comment]
It also sounded like for the upcoming milestone, the "x"s should be the default.

**Comment by samreid** [comment]
Implemented above.  Would be good to check in with @chrisklus before getting design team feedback.

**Comment by chrisklus** [comment]
@samreid and I reviewed the commits together and agree this was in good enough shape for an initial review from @amanda-phet. We didn't want to spend time pixel polishing without showing you first. Note that they can be changed from the Options dialog in addition to the query parameter.

**Comment by amanda-phet** [comment]
The x's could probably use a little polishing- it would be nice if they still looked countable even with a tall stack. For example, at 12, it is hard to tell that there are 4 x's. 
![image](https://user-images.githubusercontent.com/7852916/156008287-e057a9cf-8d8e-4607-b6b9-8b04efe7bec3.png)

Can you keep the position of the x so that it's still in the center of where a dot would be, but make the arms a little bit shorter? That would make for more space between them. I think they could also have a slightly lighter weight. 

I agree that maybe the tick marks should only appear below that horizontal line. Something like this: 
![image](https://user-images.githubusercontent.com/7852916/156008697-b61b2d2f-46e8-42fa-95a5-bcacd4d16c9e.png)

**Comment by samreid** [comment]
I addressed the requests above.  At the moment, we are using Font Awesome to render the "x" marks.  I reduced their scale to 0.8 for now.  Let me know if we should make further adjustments, or if we need more control over the "x" rendering.  @amanda-phet can you please review?

**Comment by amanda-phet** [comment]
The x's look really good to me! Should I open another issue about the tick marks?

**Comment by samreid** [comment]
Yes, please.  Thanks!

**Comment by amanda-phet** [comment]
OK, we can close this issue now.
