### ISSUE TITLE
Design Meeting Requests from Feb 23, 2020

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#41]
- [x] Top (dotplot dot) object shouldn't be highlighted when the median is selected below.
- [x] Mean (purple) predictor dragging should be continuous.
- [x] Put purple predict checkbox first
- [x] Say predict mean and predict median in the checkbox labels
- [ ] ~Moved to another issue~ #42
- [x] The mean checkbox icon should have a bar, like in the mockups
- [x] Get rid of the median bar icon in the cards accordion box on the 1st screen.
- [x] Distance (meters) font could be smaller by a pixel or two
- [x] Mean and Median read out font could be larger by a couple of pixel sizes
- [x] Balls should go behind the “Dot Plot” accordion box behind the 
- [x] In the dot plot, the dots should be smaller and go out of the clipping area at a half dot
- [x] Align the 1-16 scales in the accordian box and the soccer field 
- [ ] ~“Line Plot’ shows “x”s.  Query parameter.  Kathy also wants options menu.  maybe use MathSymbols.TIMES.~  Moved to https://github.com/phetsims/center-and-spread/issues/40
- [x] Continue using “?” for mean/median readouts with no values (so go ahead and i18n the "?")
- [x] #43

**Comment by chrisklus** [comment]
@amanda-phet All items except the ones that were moved to separate issues are ready for review if you'd like to take a look! https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.8/phet/center-and-spread_en_phet.html

**Comment by amanda-phet** [comment]
All of these look good to me!
