### ISSUE TITLE
Make start-up ball full opacity. Make to-be-kicked ball after the start up be different (leading idea is lower opacity). Goals - still something to kick, but distinguishable from the set.

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#43]

**Comment by chrisklus** [comment]
@samreid and I completed this in the commit above. @amanda-phet would like to review here? https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.8/phet/center-and-spread_en_phet.html

**Comment by amanda-phet** [comment]
This is definitely looking better to me!

**Comment by samreid** [comment]
Can this issue be closed?

**Comment by amanda-phet** [comment]
I thought we reviewed it Friday so yes it can be closed.
