### ISSUE TITLE
Address UX related TODOs in code

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#46]

**Comment by samreid** [comment]
I triaged TODOs and labeled TODO-UX accordingly.  Note some are already TODO-DESIGN which I did not change.

**Comment by chrisklus** [comment]
@samreid and I reviewed all of the TODO-UX and TODO-DESIGN, and fixed all critical ones that weren't part of other issues. Closing this issue, as the remaining TODOs can be tracked in and at the priority of  https://github.com/phetsims/center-and-spread/issues/45
