### ISSUE TITLE
Need to polish arrow within constraints of common code (head width, tail width, head height)

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#48]
From design meeting 2/16:

@samreid and I mentioned that the triangle style is the only "built in" arrow type, but we can certainly make new arrows if the "line" type is desirable.

Assigning to @amanda-phet to specify tweaks or design changes for the various arrow heads used in the sim. Maybe it would be nice to do this with @samreid and @chrisklus driving for the small adjustments needed for arrows that will stay as the triangle style.

Also leaving priority assignment for @amanda-phet.

**Comment by samreid** [comment]
UPDATE: @chrisklus and I decided to put this at low for now.  @amanda-phet please adjust as desired.

**Comment by amanda-phet** [comment]
I accidentally opened https://github.com/phetsims/center-and-spread/issues/66 not realizing this was already open.
