### ISSUE TITLE
Multi-kick animation

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#53]
Will it be important to show the next kicker in a standing pose at the front of the line before they have their leg out? For fire-on-hold and kick 5, we currently just show the next person with their leg out when they reach the front of the line.

We think it will be easier to judge how natural the current implementation vs the above behavior feels once their is varied player artwork.

**Comment by amanda-phet** [comment]
Agreed, let's see how it looks once we have the 4 new people added.

**Comment by samreid** [comment]
We started implementing this as part of https://github.com/phetsims/center-and-spread/issues/12

**Comment by chrisklus** [comment]
This is ready for review!

**Comment by chrisklus** [comment]
From having this be in the sim for a little while, I've been noticing that the single kick animation feels acceptable, though could maybe be improved with the timing of the leg (the kicking leg gets ahead of the ball). The multikick animation feels a bit jerky to me still. I'm not sure much can be done here, but wanted to note that it has felt a bit distracting and out of place with the rest of the smooth animations going on in case there was any brainstorming we could do to improve this. The line jumping up may be a bigger part of this effect than the kick animation itself.

**Comment by amanda-phet** [comment]
Discussed 3/2/22 and decided to reduce the time spent in "standing" before "kicking." I will review on my computer before closing, just to be sure I like it.

**Comment by amanda-phet** [comment]
I'm liking this change, and like how quickly a ball is kicked and in motion after pushing the "kick 1" button.
