### ISSUE TITLE
grass height needs to be polished

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-spread#54]

**Comment by samreid** [comment]
@chrisklus and I fixed this, @amanda-phet would you like any adjustments?

**Comment by amanda-phet** [comment]
I'm not exactly sure what polish happened here, but the grass seems fine to me in the dev bounds. It's a little taller than the mockup, but I don't think we need to make it shorter until/unless we update the appearance of the predict markers. 

When the browser is narrow, though, I think the grass takes up too much height (as noted in https://github.com/phetsims/center-and-spread/issues/50).
