### ISSUE TITLE
Make tick marks only visible below chart

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#56]
Noticed in https://github.com/phetsims/center-and-spread/issues/40 that the tick marks could use some refinement. 

Something like this would be nice: 

![image](https://user-images.githubusercontent.com/7852916/156008697-b61b2d2f-46e8-42fa-95a5-bcacd4d16c9e.png)

**Comment by chrisklus** [comment]
@amanda-phet would you like this for the dots as well? (that would then be consistent across all types - soccer balls, ticks marks, and dots)

**Comment by samreid** [comment]
We completed this in https://github.com/phetsims/center-and-spread/issues/40, @amanda-phet can you please review?

**Comment by amanda-phet** [comment]
Looks great to me. Thanks!
