### ISSUE TITLE
Update documentation locations

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#57]
For https://github.com/phetsims/chipper/issues/1201, update the doc locations.

**Comment by samreid** [comment]
We reaffirmed this goal in today's dev meeting.

**Comment by samreid** [comment]
I moved the documentation to the declaration site as appropriate.  Over to @chrisklus for a review.

**Comment by chrisklus** [comment]
Looks good @samreid, thanks! Closing
