### ISSUE TITLE
Change range to 15

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#63]
The range has been discussed in previous issues, but for space concerns we think making the range 1-15 would still provide the flexibility needed for showing a skewed distribution and would provide more space on the right side of the sim.

**Comment by amanda-phet** [comment]
And leave the current spacing between tick marks the same as it is now.

**Comment by samreid** [comment]
I decreased the range to 15 since it was required for https://github.com/phetsims/center-and-spread/issues/11, but I have not changed the spacing yet.

**Comment by samreid** [comment]
It felt like one of the motivating factors for this issue was so there would be more room for the checkbox panel.  But the checkbox panel was spaced based on the right edge of the number line.  So I changed it to use the right edge of the layout bounds, so there would be more space.  If that wasn't intended for the design, please let me know and it can be reverted.

Ready for code and design review.

**Comment by chrisklus** [comment]
Haha this our first issue that we both completed separately, not bad! I should have communicated earlier when i started on it, oops. But we both landed on 207, which is great news.

**Comment by chrisklus** [comment]
Code changes look good, leaving assigned for @amanda-phet.

**Comment by amanda-phet** [comment]
The left edge of the number line moved over quite a bit, so I'm not sure we got as much extra space on the right as we were hoping for. Is this because it is based on how much room the players on the left take up?

**Comment by samreid** [comment]
Yes, I was surprised to see that the number line was centered instead of us choosing a fixed location for "1", but I wasn't sure what was intended so I left it alone.  @amanda-phet please advise.

**Comment by amanda-phet** [comment]
Centered makes sense, my eye just didn't see it that way. Let's leave this as it is, since it won't hurt to have that extra space on the left when we get to the Spread screen.
