### ISSUE TITLE
Make ball full opacity once kicker is "poised to kick" 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#64]

**Comment by chrisklus** [comment]
I renamed the issue based on my understanding from discussion in design meeting + the name changes of the kicking images.

**Comment by samreid** [comment]
In 50086ab2034e9c2f3db8ee9f13aa5204ce8502a3 we reduced the "poised to kick" time from 0.3 seconds to 0.075 seconds, so it is difficult to see this problem.  Does it still warrant effort for this sprint or for the 1.0 production publication?

**Comment by amanda-phet** [comment]
That is a good point @samreid , it's not a problem anymore. I'm fine not making this change at all, either for the classroom prototype or 1.0 publication.
