### ISSUE TITLE
Change default plot type to line plot

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#65]
For the purposes of the classroom pilot, I'd like the default plot type selection to be Line Plot. We may change this for 1.0, but would like this for the prototype. 

![image](https://user-images.githubusercontent.com/7852916/156473324-c43056f0-36d3-4c42-8906-3a026ea8815f.png)

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by amanda-phet** [comment]
Perfect, thank you!
