### ISSUE TITLE
Increase TIME_BETWEEN_RAPID_KICKS

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#67]
At today's design meeting, we reduced the time of the "poised to kick" pose, which looks great!  Afterwards, @chrisklus pointed out that means the "Kick 5" now happens too quickly and it is confusing what is happening.  We proposed to increase the `TIME_BETWEEN_RAPID_KICKS`.  We'll commit a proposal for review and discussion.  We also noted this timing better matches the "autofire" press and hold behavior when holding down the "Kick 1" button.

**Comment by samreid** [comment]
Fixed in the commit and seems to be working nicely.  @amanda-phet can you please review and advise?  Close if all is well.

**Comment by amanda-phet** [comment]
Hm, I am playing with all of this now and I thin the time of "poised to kick" is looking too short now, but the increase in time between rapid kicks make the sim feel a bit laggy. Maybe we can tune this together on Friday morning?

**Comment by amanda-phet** [comment]
Closing this for now since I am not sure what I would want to be different, and my experience of wanting to kick 15 quickly might not match a more common user experience. Also, now that the students are shown individually, I think this looks nice.
