### ISSUE TITLE
Change player spacing

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#68]
Related to https://github.com/phetsims/center-and-spread/issues/12, @chrisklus and I adjusted the spacing between the soccer players, and we accidentally tried a spacing that put the second and later soccer players offscreen.  However, it looked very clean and amazing.  Here's an example of how it looked:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/679486/156497935-3bc6e34c-708d-4dfd-bdc9-cc80978dd1c0.png">

After seeing this, the other designs seemed cluttered and unnecessary.  In our recollection, it seemed important to show that there were 15 maximum kickable balls, but in my opinion the student will learn that in other ways and we shouldn't try to show all the kickers at once.

**Comment by amanda-phet** [comment]
Noting that this scenario looks inappropriate, and is another reason to reconsider showing the tight line of students.
![image](https://user-images.githubusercontent.com/7852916/156795496-5587ed92-f613-4629-9cd5-4b1889905bbc.png)

**Comment by amanda-phet** [comment]
I can't remember the motivation for showing the line, and will review meeting notes to remember. 

If the reason is to show that there are 15 balls/kicks/players, we could show a stack of transparent balls being depleted with each kick.

**Comment by amanda-phet** [comment]
Let's make the change to showing one player at a time, and revert later if I remember a good reason for showing the entire line.

**Comment by amanda-phet** [comment]
Looks good to me. Thanks!
