### ISSUE TITLE
Should the "Kick 1" and "Kick 10" button translations factor out "Kick" and use templating?

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#7]
Sam Reid  8 hours ago
For i18n “kick”, should we disallow clients from changing the number by using a template variable, like Kick {{NUMBER}}, or leave them full flexibility to phrase it as they see fit?

Amanda McGarry  8 hours ago
I can't recall having a number be translatable for any sim I've worked on. Do you have an example of a precedent for this?

Sam Reid  8 hours ago
My intuition is that it will be clearer for the translator to have full control of this part.  Like if in Chinese it is conventional to say 踢一個球 instead of 踢 1

Chris Klusendorf  7 hours ago
That sounds good to me, and we did find some numbers in string files, so there are precedents

Amanda McGarry  7 hours ago
Can someone point me to a sim that does this? It's not a question I remember being asked before, so just curious about when we've done it before. If you recommend it then I don't see why not?

Sam Reid  4 hours ago
I’m not sure of the search CK ran to find numbers in the strings file, I’ll wait for him to chime in on that part.

Chris Klusendorf  2 hours ago
it’s hard to narrow down everything like this, but i found a similar case in coulomb’s law:
  "units.atomicLegendScale": {
    "value": "10 pm"
  },
  "units.macroLegendScale": {
    "value": "1 cm"
  },

Chris Klusendorf  2 hours ago
I’m pretty indifferent - both approaches seem fine to me. We could factor out a string like “Kick {{number}}” or give translators more control for a case like @samreid described above

Amanda McGarry  1 hour ago
I’m not sure what is best here either. Maybe this question/discussion is worthy of an issue, at least to document.

**Comment by samreid** [comment]
My recommendation is to set it up like:

```json
  "kick1": {
    "value": "Kick 1"
  },
  "kick10": {
    "value": "Kick 10"
  }
```

This gives the translators flexibility to frame it as appropriate for their language.  Like the argument above:

> Like if in Chinese it is conventional to say 踢一個球 (kick a single ball) instead of 踢 1 (Kick 1)

In previous meetings, @jonathanolson also advocated for translators to have this level of flexibility, and it was my understanding that the team was in agreement.  I don't see the advantage of enforcing a string templating pattern here.

**Comment by amanda-phet** [comment]
>In previous meetings, @jonathanolson also advocated for translators to have this level of flexibility, and it was my understanding that the team was in agreement. I don't see the advantage of enforcing a string templating pattern here.

I wasn't aware of previous meetings or consensus on this issue, and assumed that since it was asked as a question there wasn't a clear answer. Since there has been previous discussion about this case, I don't see why we shouldn't go with @samreid 's recommendation.

**Comment by samreid** [comment]
@chrisklus anything else here?  Can this issue be closed?

**Comment by chrisklus** [comment]
I think we're all set, thanks all. Closing

**Comment by samreid** [comment]
Since we changed a button to be dynamic, we need the template.  Then it also made sense to reuse the template for the Kick 1 button, so they match.  So I added kickValue and remove kick1 and kick5.
