### ISSUE TITLE
PhET-iO needs for classroom prototype

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/center-and-spread#71]
If possible, we might want the following instrumented so that our partner can build a wrapper around the sim to challenge students to predict where the mean and/or median is, and get feedback about how close they are to the actual value(s). 

- [x] instrument values for mean and median 
- [x] instrument values for prediction markers

It would be good to consider if this is feasible for the classroom prototype milestone.

**Comment by samreid** [comment]
@chrisklus and I added support in the commit.  Ready for review.

**Comment by amanda-phet** [comment]
@samreid kindly shared these IDs for me to review

`centerAndSpread.meanAndMedianScreen.model.meanPredictionProperty`
`centerAndSpread.meanAndMedianScreen.model.medianPredictionProperty`
`centerAndSpread.meanAndMedianScreen.model.meanValueProperty`
`centerAndSpread.meanAndMedianScreen.model.medianValueProperty`

`centerAndSpread.medianScreen.model.meanPredictionProperty`
`centerAndSpread.medianScreen.model.medianPredictionProperty`
`centerAndSpread.medianScreen.model.meanValueProperty`
`centerAndSpread.medianScreen.model.medianValueProperty`

I'm not sure we need the `meanPredictionProperty` and `meanValueProperty` for the Median screen. I wouldn't get rid of `meanValueProperty` since that value might be meaningful, but it might be confusing to an instructional designer to see `meanPredictionProperty` if there is no mean prediction tool on that screen. 

@samreid do you recommend removing that or leaving it?

**Comment by samreid** [comment]
@arouinfar and @pixelzoom recently had a discussion about including features that may not be present in the sim.  It seemed like the recommendation is to keep them?  @arouinfar or @pixelzoom what do you recommend?

**Comment by samreid** [comment]
It looks like the consensus in https://github.com/phetsims/geometric-optics-basics/issues/3#issuecomment-1050287506 was to prefer a single tree?  Does that apply here across screens?

**Comment by arouinfar** [comment]
If it's a feature (or data) related to a later screen that could be added to an earlier screen and be functional/appropriate then it's fine to keep in the tree. Examples of this would include the teeth & ear mutations in the first screen of Natural Selection or even the series ammeter in CCK (if we would have designed the tree after our recent discussion). 

If the elements that @amanda-phet requested to have trimmed from the tree are not functional or don't make sense to be turned on for that particular screen, it makes sense to remove them.

**Comment by kathy-phet** [comment]
Hi Sam, There are two cases: 
1) If the feature is not and would not make sense to be available on a screen, then it needs to be removed from the tree for that Screen. 
2) If the feature is something that is not available on the screen, but would make sense to pedagogically have  on the screen and it would fit design wise, then it can be in the tree, just we would not feature it. 

So Geometric Optics Basics is a subset of Geometrics Optics, but you can start with the Basics version and through PhET-iO layer in a few more features from the full set if you want.

**Comment by kathy-phet** [comment]
Agree with what Amy said.

**Comment by samreid** [comment]
Thanks, it sounds like we should uninstrument the mean prediction property on the 1st screen here because there is no way to turn on the mean prediction arrow on the 1st screen (unless we add that as a new feature).  We'll work on that shortly.

**Comment by samreid** [comment]
Implemented, over to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Thanks for sharing what has been discussed and decided in the past. I think this was the right call and all looks good to me!
