### ISSUE TITLE
PhET-iO Save/Restore has wrong transparency for initial ball

### ISSUE THREAD

**Issue by samreid** [phetsims/center-and-spread#73]
PhET-iO Save/Restore has wrong transparency for initial ball

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/679486/156953405-45ceb737-0a6e-4d3a-b649-1c1f721660c0.png">

**Comment by chrisklus** [comment]
@samreid and I fixed this above, @Nancy-Salpepi can you please review and close if fixed? thank you!

**Comment by Nancy-Salpepi** [comment]
This looks fixed as well. Closing.
