### ISSUE TITLE
Ball highlights not working correctly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-spread#74]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/781 I am noticing 2 issues with the ball highlights on the Median Screen (but I'm assuming they are related):
1. The highlights showing the median will disappear if the Median Checkbox in the Distance Panel is checked AFTER balls are kicked with the Median Checkbox in the Play Area checked.   

2. If another ball is kicked after doing the above, there may be no highlight (for odd # of balls) or only one highlight (for even number of balls). Eventually, it starts to work correctly again, but when that happens seems to vary. 

* If you check BOTH median checkboxes BEFORE kicking the ball, the highlights work correctly. 

* I also saw this on master. No errors appeared in the console. 

**Steps to reproduce**
1. On the Median Screen, check the Median Checkbox in the play area
2. Press the Kick 1 Button
3. Check the Median Checkbox in the distance panel--the ball highlight will disappear
4. Press the Kick 1 Button --only 1 highlight will appear

This issue is also seen when starting with the Kick 5 button. 

**Visuals**
<img width="187" alt="Screen Shot 2022-03-07 at 7 57 00 AM" src="https://user-images.githubusercontent.com/87318828/157049127-741cf7d4-d86c-40af-9e63-e7b2bd8eb349.png">

https://user-images.githubusercontent.com/87318828/157051530-b6476e6c-be2d-4c31-aa3e-a4206eb5958b.mp4

https://user-images.githubusercontent.com/87318828/157051561-fb555f76-cdba-479e-8e6a-8b7bddd0c017.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36
Language: en-US
Window: 980x467
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
In Studio, launching sim with both Median checkboxes checked results in no highlights on the soccer balls (it works correctly if the Median checkbox in the panel is unchecked). 

1. On either screen, check both Median checkboxes
2. Press 'Kick 5' button once
3. Launch sim

https://user-images.githubusercontent.com/87318828/157743195-7bbf5370-4def-4263-973f-660fe4948a42.mp4

**Comment by amanda-phet** [comment]
This seems like a good one to figure out for the classroom prototype

**Comment by samreid** [comment]
@chrisklus and I fixed the problem.  The commit isn't showing in the issue thread yet, but GitHub has registered the push, so it is ready for testing.  It will probably show below this comment soon.  @Nancy-Salpepi can you please test on master?  Close if all is well.

**Comment by Nancy-Salpepi** [comment]
Looks good in the PhET brand sim and in the Studio wrapper. Closing.
