### ISSUE TITLE
launched sim shows wrong person 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-spread#86]
**Test device**

**Operating System**
MacBook Air (m1 chip)

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/781

The launched sim always begins with the woman. Also, the ball isn't transparent. 
If you press 'kick 1' the woman makes a kicking motion but the ball doesn't move--this will always lead to one ball being "left over" at the end with no way of kicking it. 

**Steps to reproduce**
1. In Studio: on either screen press 'Kick 1" once
2. launch the sim --it shows the woman instead of the girl and the ball isn't transparent.
3. Press 'Kick 1' button --woman kicks but no ball is launched into the air
4. Press 'Kick 1' button again--the person changes to the girl and she kicks the ball. The girl then changes to the man. 

**Visuals**

https://user-images.githubusercontent.com/87318828/157308854-a638280b-7ad5-4051-ab1c-ada7dc933674.mp4

* at the end there is one ball left next to the '1'
<img width="799" alt="Screen Shot 2022-03-08 at 2 23 03 PM" src="https://user-images.githubusercontent.com/87318828/157310724-ffb47236-baa0-4622-8ac8-436be6e1575c.png">

**Comment by Nancy-Salpepi** [comment]
Without pressing anything in Studio, if I launch the sim and press 'kick 1' the woman will still kick nothing on the first attempt.

**Comment by samreid** [comment]
@chrisklus and I determined this seems related to #92

**Comment by samreid** [comment]
We fixed the display of the soccer player image, but still experience these related problems:

* https://github.com/phetsims/center-and-spread/issues/92
* A duplicate card appears in the launched sim, that tracks with the first card.
* #73

**Comment by Nancy-Salpepi** [comment]
The soccer player image is now correct when the sim is launched. Closing.
