### ISSUE TITLE
Balls not draggable in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-spread#90]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
Safari and Chrome

Also seen on win10 + Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/781 

Any balls kicked in Studio are not moveable in the launched sim. Only balls kicked in the launched sim are draggable. 
The tiles and Predict Mean/Mode arrows are all moveable. 

**Steps to reproduce**
1. In Studio, on either screen, press the 'Kick 5' button once
2. Launch the sim
3. Try to move the balls
4. Press 'Kick 5' in the launched sim--those balls will be draggable. 

**Visuals**

https://user-images.githubusercontent.com/87318828/157677069-a05f62a6-0694-4ccc-a6b7-e24432bd90a6.mp4

**Comment by amanda-phet** [comment]
This seems like a priority for the classroom prototype since we expect to use this feature in an integration.

**Comment by Nancy-Salpepi** [comment]
Looks fixed on master. Closing.
